In [1]:
import json
import pandas as pd

file = "bulk.json"

In [2]:
data = pd.read_json(file)
length = len(data)

In [55]:
wind = []
rain_ttl = data["rain"]
date = data["dt_iso"]

#pd.DataFrame("Wind")

In [57]:
rain_df = pd.DataFrame({"Rainfall" : rain_ttl,
            "Date": date})
rain_df.dropna()

                          Rainfall                           Date
0                     {'3h': 2.06}  2015-06-12 01:00:00 +0000 UTC
1                     {'3h': 0.67}  2015-06-12 23:00:00 +0000 UTC
2                     {'3h': 0.67}  2015-06-13 01:00:00 +0000 UTC
3                     {'3h': 0.84}  2015-06-13 02:00:00 +0000 UTC
6                   {'3h': 5.2175}  2015-06-15 01:00:00 +0000 UTC
7                     {'3h': 1.16}  2015-06-19 23:00:00 +0000 UTC
10                  {'3h': 0.6925}  2015-06-22 23:00:00 +0000 UTC
11                    {'3h': 1.22}  2015-06-24 09:00:00 +0000 UTC
12     {'3h': 0.35000000000000003}  2015-06-24 11:00:00 +0000 UTC
13     {'3h': 0.35000000000000003}  2015-06-24 12:00:00 +0000 UTC
14     {'3h': 0.35000000000000003}  2015-06-24 13:00:00 +0000 UTC
19                  {'3h': 3.0625}  2015-06-24 20:00:00 +0000 UTC
20                  {'3h': 3.0625}  2015-06-24 21:00:00 +0000 UTC
21                    {'3h': 1.44}  2015-06-24 23:00:00 +0000 UTC
22                    {'3h': 1.44}  2015-06-25 00:00:00 +0000 UTC
23                    {'3h': 1.44}  2015-06-25 01:00:00 +0000 UTC
27                   {'3h': 0.405}  2015-06-25 05:00:00 +0000 UTC
28                   {'3h': 0.405}  2015-06-25 07:00:00 +0000 UTC
51                  {'3h': 5.7075}  2015-06-26 20:00:00 +0000 UTC
58                   {'3h': 1.755}  2015-06-27 03:00:00 +0000 UTC
78                    {'3h': 0.46}  2015-06-27 23:00:00 +0000 UTC
81                    {'3h': 0.89}  2015-06-28 03:00:00 +0000 UTC
85                    {'3h': 0.56}  2015-06-28 07:00:00 +0000 UTC
86                    {'3h': 0.56}  2015-06-28 08:00:00 +0000 UTC
87                    {'3h': 0.56}  2015-06-28 09:00:00 +0000 UTC
88                   {'3h': 5.655}  2015-06-28 10:00:00 +0000 UTC
90                   {'3h': 5.655}  2015-06-28 12:00:00 +0000 UTC
91                   {'3h': 0.665}  2015-06-28 13:00:00 +0000 UTC
92                   {'3h': 0.665}  2015-06-28 14:00:00 +0000 UTC
99                  {'3h': 4.1225}  2015-06-28 21:00:00 +0000 UTC
...                            ...                            ...
27805                 {'3h': 0.56}  2018-11-14 03:00:00 +0000 UTC
27808   {'3h': 0.9400000000000001}  2018-11-14 06:00:00 +0000 UTC
27809   {'3h': 0.9400000000000001}  2018-11-14 07:00:00 +0000 UTC
27811                 {'3h': 0.32}  2018-11-14 09:00:00 +0000 UTC
27812                 {'3h': 0.32}  2018-11-14 10:00:00 +0000 UTC
28147                 {'3h': 0.23}  2018-11-28 11:00:00 +0000 UTC
28148                 {'3h': 0.23}  2018-11-28 12:00:00 +0000 UTC
28149                 {'3h': 0.23}  2018-11-28 13:00:00 +0000 UTC
28166                {'3h': 7.465}  2018-11-29 06:00:00 +0000 UTC
28167                {'3h': 7.465}  2018-11-29 07:00:00 +0000 UTC
28168              {'3h': 11.0525}  2018-11-29 08:00:00 +0000 UTC
28169              {'3h': 11.0525}  2018-11-29 09:00:00 +0000 UTC
28170              {'3h': 11.0525}  2018-11-29 10:00:00 +0000 UTC
28171                 {'3h': 5.68}  2018-11-29 11:00:00 +0000 UTC
28172                 {'3h': 5.68}  2018-11-29 12:00:00 +0000 UTC
28173                 {'3h': 5.68}  2018-11-29 13:00:00 +0000 UTC
28191                {'3h': 0.355}  2018-11-30 07:00:00 +0000 UTC
28387  {'3h': 0.34500000000000003}  2018-12-08 11:00:00 +0000 UTC
28388  {'3h': 0.34500000000000003}  2018-12-08 12:00:00 +0000 UTC
28389  {'3h': 0.34500000000000003}  2018-12-08 13:00:00 +0000 UTC
28404   {'3h': 0.5650000000000001}  2018-12-09 04:00:00 +0000 UTC
28405               {'3h': 0.8325}  2018-12-09 05:00:00 +0000 UTC
28406               {'3h': 0.8325}  2018-12-09 06:00:00 +0000 UTC
28407               {'3h': 0.8325}  2018-12-09 07:00:00 +0000 UTC
29213               {'3h': 1.4325}  2019-01-11 20:00:00 +0000 UTC
29214               {'3h': 1.4325}  2019-01-11 21:00:00 +0000 UTC
29215               {'3h': 1.4325}  2019-01-11 22:00:00 +0000 UTC
29216                {'3h': 0.705}  2019-01-11 23:00:00 +0000 UTC
29217                {'3h': 0.705}  2019-01-12 00:00:00 +0000 UTC
29218                {'3h': 0.705}  2019-01-12 01:00:00 +0000 UTC

[2880 rows x 2 columns]